Fix bug when loading packed-keras models
Loading a keras model gives this error:
```
TypeError: Can't instantiate abstract class PackedKerasModel with abstract methods get_model
```

Since the `get_model` method is only relevant for training this error does not need to be raised until the `.fit` method is called.