workflow execution failed due to incorrect slice args...
The variable selection should probably be part of the architecture config.

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/fv3fit/train_microphysics.py", line 362, in <module>
    main(config)
  File "/usr/local/lib/python3.8/dist-packages/fv3fit/train_microphysics.py", line 218, in main
    model = config.build(train_set)
  File "/usr/local/lib/python3.8/dist-packages/fv3fit/train_microphysics.py", line 114, in build
    return self._model.build(data)
  File "/usr/local/lib/python3.8/dist-packages/fv3fit/emulation/models/microphysics.py", line 292, in build
    model = self._build_base_model(data)
  File "/usr/local/lib/python3.8/dist-packages/fv3fit/emulation/models/microphysics.py", line 245, in _build_base_model
    return MicrophysicsConfig(
  File "/usr/local/lib/python3.8/dist-packages/fv3fit/emulation/models/microphysics.py", line 149, in build
    **self._get_direct_outputs(data, hidden),
  File "/usr/local/lib/python3.8/dist-packages/fv3fit/emulation/models/microphysics.py", line 91, in _get_direct_outputs
    out_ = FieldOutput(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 951, in __call__
    return self._functional_construction_call(inputs, args, kwargs,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 1090, in _functional_construction_call
    outputs = self._keras_tensor_symbolic_call(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 822, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 863, in _infer_output_signature
    outputs = call_fn(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/autograph/impl/api.py", line 670, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /usr/local/lib/python3.8/dist-packages/fv3fit/emulation/layers/fields.py:92 call  *
        tensor = self.denorm(tensor)
    /usr/local/lib/python3.8/dist-packages/fv3fit/emulation/layers/normalization.py:161 call  *
        return tensor * self.sigma + self.mean
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/math_ops.py:1180 binary_op_wrapper
        raise e
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/math_ops.py:1164 binary_op_wrapper
        return func(x, y, name=name)
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/math_ops.py:1486 _add_dispatch
        return gen_math_ops.add_v2(x, y, name=name)
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/gen_math_ops.py:481 add_v2
        _, _, _op, _outputs = _op_def_library._apply_op_helper(
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/op_def_library.py:748 _apply_op_helper
        op = g._create_op_internal(op_type_name, inputs, dtypes=None,
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/func_graph.py:590 _create_op_internal
        return super(FuncGraph, self)._create_op_internal(  # pylint: disable=protected-access
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py:3528 _create_op_internal
        ret = Operation(
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py:2015 __init__
        self._c_op = _create_c_op(self._graph, node_def, inputs,
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py:1856 _create_c_op
        raise ValueError(str(e))

    ValueError: Dimensions must be equal, but are 69 and 79 for '{{node cloud_water_mixing_ratio_after_precpd/denormalized_cloud_water_mixing_ratio_after_precpd/add}} = AddV2[T=DT_FLOAT](cloud_water_mixing_ratio_after_precpd/denormalized_cloud_water_mixing_ratio_after_precpd/mul, cloud_water_mixing_ratio_after_precpd/denormalized_cloud_water_mixing_ratio_after_precpd/add/ReadVariableOp)' with input shapes: [?,69], [79].