notes: todos for tomorrow
* need to use model.losses in the training loop
* loss value is nan when trained with real data. write an integration
test

Traceback (most recent call last):
  File "/home/noahb/miniconda3/envs/fv3net/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/noahb/miniconda3/envs/fv3net/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/scratch/noahb/fv3net/external/fv3fit/fv3fit/train_emulator.py", line 94, in <module>
    main(config)
  File "/scratch/noahb/fv3net/external/fv3fit/fv3fit/train_emulator.py", line 70, in main
    emulator.batch_fit(train_dataset.shuffle(100_000), validation_data=test_dataset)
  File "/scratch/noahb/fv3net/external/fv3fit/fv3fit/emulation/thermobasis/emulator.py", line 307, in batch_fit
    info = self.step(in_, out)
  File "/scratch/noahb/fv3net/external/fv3fit/fv3fit/emulation/thermobasis/emulator.py", line 264, in step
    raise ValueError("Loss is NaN")
ValueError: Loss is NaN